config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :organizations
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  resources :users, only: [:show]

  namespace :admin do
    mount GoodJob::Engine => 'background_jobs'
    mount RailsMiniProfiler::Engine => 'requests' if Rails.env.development?
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/organization.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: organizations
#
#  id                :uuid             not null, primary key
#  archived_at       :datetime
#  domain            :text
#  name              :text             not null
#  slug              :text
#  social_media_urls :jsonb
#  subdomain         :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :uuid             not null
#
# Indexes
#
#  index_organizations_on_domain     (domain) UNIQUE
#  index_organizations_on_name       (name) UNIQUE
#  index_organizations_on_slug       (slug) UNIQUE
#  index_organizations_on_subdomain  (subdomain) UNIQUE
#  index_organizations_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_7b93e0061c  (user_id => users.id)
#
class Organization < ApplicationRecord
  include Archivable

  # Track and store changes to this model
  has_paper_trail

  # Use the name attribute as the slug in URLs, store a history of old slugs to redirect to the latest
  extend FriendlyId
  friendly_id :name, use: :history
  # Regenerate the slug and store the old version when the underlying attribute is updated
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

  validates :name, :subdomain, :domain, presence: true
  validates :name, :subdomain, :domain, uniqueness: true

  validate :logo_is_correct_format

  belongs_to :admin_user, class_name: 'User'
  has_many :users, inverse_of: :organization, dependent: :nullify

  has_rich_text :description

  has_one_attached :logo

  private

  def logo_is_correct_format
    return if !logo.attached? && logo.blob.content_type.starts_with?('image/')

    logo.purge
    errors.add(:logo, 'is not a valid image format.')
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

# This controller defines all actions available to Organizations
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations or /organizations.json
  def index
    @organizations = authorize Organization.all
  end

  # GET /organizations/1 or /organizations/1.json
  def show
    authorize @organization

    # Redirect to the latest URL for the organization if an old slug was used
    redirect_to @organization, status: :moved_permanently if request.path != organization_path(@organization)
  end

  # GET /organizations/new
  def new
    @organization = authorize Organization.new
  end

  # GET /organizations/1/edit
  def edit
    authorize @organization
  end

  # POST /organizations or /organizations.json
  def create
    @organization = authorize Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to organization_url(@organization), notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    authorize @organization

    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organization_url(@organization), notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    authorize @organization
    @organization.archive!

    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = Organization.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # Render the 404 page if the record cannot be found with the given slug
    render file: Rails.public_path.join('404.html'), status: :not_found and return
  end

  # Only allow a list of trusted parameters through.
  def organization_params
    params.require(:organization).permit(:name, :description, :logo, :domain, :subdomain, :social_media_urls)
  end
end

app/helpers/organizations_helper.rb
# frozen_string_literal: true

# Adds helper methods available to Organizations
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :admin_user %>
    <%= f.input :name %>
    <%= f.input :slug %>
    <%= f.input :description %>
    <%= f.input :domain %>
    <%= f.input :subdomain %>
    <%= f.input :social_media_urls %>
    <%= f.input :archived_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<div id="<%= dom_id organization %>">
  <p>
    <strong>Admin user:</strong>
    <%= organization.admin_user_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= organization.name %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= organization.slug %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= organization.description %>
  </p>

  <p>
    <strong>Domain:</strong>
    <%= organization.domain %>
  </p>

  <p>
    <strong>Subdomain:</strong>
    <%= organization.subdomain %>
  </p>

  <p>
    <strong>Social media urls:</strong>
    <%= organization.social_media_urls %>
  </p>

  <p>
    <strong>Archived at:</strong>
    <%= organization.archived_at %>
  </p>

</div>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render "form", organization: @organization %>

<br>

<div>
  <%= link_to "Show this organization", @organization %> |
  <%= link_to "Back to organizations", organizations_path %>
</div>

app/views/organizations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Organizations</h1>

<div id="organizations">
  <% @organizations.each do |organization| %>
    <%= render organization %>
    <p>
      <%= link_to "Show this organization", organization %>
    </p>
  <% end %>
</div>

<%= link_to "New organization", new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render "form", organization: @organization %>

<br>

<div>
  <%= link_to "Back to organizations", organizations_path %>
</div>

app/views/organizations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @organization %>

<div>
  <%= link_to "Edit this organization", edit_organization_path(@organization) %> |
  <%= link_to "Back to organizations", organizations_path %>

  <%= button_to "Destroy this organization", @organization, method: :delete %>
</div>